name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write   # ⭐ IMPORTANT FIX

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. SAST - CodeQL (UPDATED VERSION)
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    # 3. Install dependencies
    - name: Install Dependencies
      run: pip install flask

    # 4. Build Docker Image
    - name: Build Docker Image
      run: docker build -t devsecops-demo .

    # 5. Container Scan (Trivy)
    - name: Scan Docker Image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: devsecops-demo