name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. SAST - CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    # 3. Install Dependencies
    - name: Install Dependencies
      run: pip install flask

    # 4. Dependency Scan (basic check)
    - name: Check Dependencies
      run: pip list

    # 5. Build Docker Image
    - name: Build Docker Image
      run: docker build -t devsecops-demo .

    # 6. Container Scan (Trivy)
    - name: Scan Docker Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-demo

    # 7. Run App (for DAST later)
    - name: Run App
      run: |
        docker run -d -p 5000:5000 devsecops-demo
        sleep 10